# frozen_string_literal: true

source "http://rubygems.org"

gem "activerecord", "~> 5.2", ">= 5.2.0", require: "active_record"
gem "sinatra"
gem "sinatra-activerecord", require: "sinatra/activerecord"
gem "sinatra-flash"
gem "standalone_migrations"
gem "pry"
gem "rake"
gem "require_all"
gem "shotgun"
gem "bcrypt"
gem "mysql2"
gem "thin"
gem "tux"
gem "thor"
gem "puma"

group :test do
  gem "capybara"
  gem "rack-test"
  gem "rspec"
  # gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
